### ISSUE TITLE
"Failed to init ANT+ dongle": Tacx ANT+ Dongle

### ISSUE THREAD

**Issue by Cacauu** [pepelkod/AntBridge#3]
After getting a Tacx Fortius Multiplayer and buying a Tacx ANT+ dongle, I tried to use AntBridge on my raspberry pi. Installation was no problem, but - with both, the trainer and dongle connected, I always get this message:
```Fortius initialized
ANT+ dongle initialized
Failed ANT init
Failed to init ANT+ dongle
```

This is the output from `lsusb`:
```Bus 001 Device 008: ID 0fcf:1004 Dynastream Innovations, Inc. ANT2USB
Bus 001 Device 007: ID 3561:1932  
Bus 001 Device 006: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 001 Device 004: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp. LAN9500 Ethernet 10/100 Adapter / SMSC9512/9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

I've tried unplugging the dongle several times without success. Is it possible that this is not working because my dongle is not _1008_ or _1009_ but _1004_? Is there something I could change to make it work with this kind of dongle? Which dongle are you using?

I'd very much appreciate if you could give me a hint of where to find my error... Thanks!

**Comment by pepelkod** [comment]
First, you must have permissions to access the device.  I run it as 'sudo'.

As for the VID PID I just put an update in that should accept 1004.  See if this works.  Email me if it doesn't

-Doug
________________________________

**Comment by Cacauu** [comment]
Thank you for your quick answer!

I'm still waiting for my second ANT+ dongle to test it, but it seems to be working now, at least the only errors that are being logged are `usb read errors` from the Fortius (which might be normal). I wasn't able to find the trainer on my Forerunner 935 (the only ANT+ device available here) so I don't know if that is normal or not. I'll update once I get my second dongle for the mac :)
